using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Vulpine.Core.Draw.Exceptions
{
    /// <summary>
    /// This is the base class for all exceptions generated by and
    /// pretaning to objects within the imaging library.
    /// </summary>
    public class ImagingException : Exception
    {
        /// <summary>
        /// Creates a new exception with the given message.
        /// </summary>
        /// <param name="msg">A message explaning the nature and
        /// cause of the exception</param>
        public ImagingException(string msg) : base(msg) { }

        /// <summary>
        /// Creates a new image exception. Sub-clases should provide
        /// a custom message by overriding the virtual Message property.
        /// </summary>
        public ImagingException() : base() { }
    }
}
